id: P004530
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3431
  title: རིགས་པ་དྲུག་བཅུ་པའི་འགྲེལ་པ།
  author: ''
  volumes:
    5f481037908d4909bdc3e18ff9b86da4:
      image_group_id: I3CN4019
      title: ''
      volume_number: 1
      total_pages: 408
      base_file: v001.txt
