id: I01CAA23B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:43:58+00:00'
last_modified: '2022-06-08T01:44:03.201023+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3431
  title: རིགས་པ་དྲུག་བཅུ་པའི་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DB68:
      image_group_id: I3CN4019
      title: ''
      total_pages: 408
      order: 1
      base_file: DB68.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
